### PR TITLE
Adding free book "Automate the Boring Stuff with Python"

### PR DESCRIPTION
**Pull request by asweigart**
This PR adds the beginner book, "Automate the Boring Stuff with Python" from No Starch Press, which is available for free online under a Creative Commons license.

### CODE REVIEW

**Comment by Michael0x2a** [comment]
Awesome, this looks like a cool resource -- I'm definitely going to add this to my own personal reading list!

Some comments about your PR:

I'm thinking of changing the description to something roughly like:

> A pragmatic introductory text that teaches how to use Python to to automate common tasks such as manipulating word docs or scraping web pages. The book assumes no prior experience at coding, though the material covered will be useful for both beginners and experts. From the author of [Invent with Python][python-invent]. 

...though I don't think this really captures the emphasis on pragmatism that your original description had, which I really liked. Do you have any suggestions regarding this?

I'm also planning on moving your resource down a few slots -- I order the resources roughly based on how general/specific they are, and I think your resource would fall roughly in the middle of that spectrum.

It also looked like your "remove trailing whitespace" commit was a little over-zealous -- suffixing a line with two spaces adds a line break in github-flavored markdown, which is why each link to a resource had two spaces afterwards. I can fix this pretty easily myself though, if needed.

If you're ok with those changes, I can go ahead merge them!

**Comment by asweigart** [comment]
Those changes sound good. How about this for the text:

A pragmatic text for complete beginners that teaches how to use Python to to automate common tasks such as web scraping, updating Excel spreadsheets, or sending emails and texts. This is a book for people who want practical coding skills, rather than becoming software engineers or learning computer science. Experienced Python developers will find the third-party modules explained in the second half of the book helpful. From the author of [Invent with Python][python-invent].

**Comment by Michael0x2a** [comment]
Apologies for the delay, but your pull request (sans the white-space removal commit) has been merged here: https://github.com/Michael0x2a/curated-programming-resources/pull/8.

**Comment by asweigart** [comment]
Thanks!

**Pull request closed without merging**
